name: clinical_decision_support
description: A clinical decision support mobile application for X-ray analysis.
publish_to: 'none'
version: 2.6.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  
  # Networking
  dio: ^5.4.0
  http_parser: ^4.0.2

  # File/Image Handling
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # UI Utilities
  google_fonts: ^8.0.1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^32.2.3
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  painter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.10"

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  macos:
    generate: true
    image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.png"
  branding: "assets/logo.png"
  color_dark: "#121212"
  image_dark: "assets/logo.png"
  branding_dark: "assets/logo.png"

  android_12:
    image: "assets/logo.png"
    icon_background_color: "#FFFFFF"
    image_dark: "assets/logo.png"
    icon_background_color_dark: "#121212"

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
